package Modelos;

import java.util.List;

/**
 * Centraliza todos os termos e regras utilizados pelo detector.
 * <p>
 * A classe contém apenas constantes e não pode ser instanciada.
 */
public final class CatalogoGolpes {

    public static final List<String> TERMOS_URGENCIA = List.of(
            "urgente",
            "agora",
            "imediatamente",
            "ultima chance",
            "na hora",
            "corre",
            "rapidinho",
            "o quanto antes",
            "sem demora",
            "ainda hoje",
            "hoje mesmo",
            "pra hoje",
            "para hoje",
            "ultimos minutos",
            "ultimas vagas",
            "tempo limitado",
            "expira hoje",
            "vai expirar",
            "antes que expire",
            "nao perca tempo",
            "responda rapido",
            "resolve agora",
            "so ate hoje",
            "pra ja",
            "para ja",
            "responda agora",
            "confirme agora mesmo",
            "nao desligue",
            "nao conte para ninguem",
            "mantenha isso em segredo",
            "sigilo absoluto"
    );

    public static final List<String> TERMOS_PROMESSA_FINANCEIRA = List.of(
            "premio",
            "ganhou",
            "ganhar",
            "ganhe",
            "sorteado",
            "dinheiro facil",
            "dinheiro rapido",
            "acaba de receber",
            "voce recebeu",
            "valor liberado",
            "valor disponivel",
            "saldo liberado",
            "promocao",
            "promo",
            "bolada no teu nome",
            "bolada no seu nome",
            "grana parada te esperando",
            "grana te esperando",
            "foi premiado",
            "foi premiada",
            "premiacao",
            "recompensa",
            "bonus exclusivo",
            "bonus liberado",
            "credito disponivel",
            "credito liberado",
            "dinheiro esperando",
            "valor a receber",
            "resgate seu valor",
            "resgate seu premio",
            "cupom premiado",
            "raspadinha premiada",
            "presente surpresa",
            "beneficio liberado",
            "beneficio aprovado",
            "cashback",
            "cashback liberado",
            "sorteio exclusivo",
            "contemplacao",
            "receba",
            "receber",
            "fature",
            "lucre",
            "lucro",
            "renda extra",
            "retorno financeiro",
            "saque seu dinheiro",
            "resgate seu dinheiro"
    );

    public static final List<String> TERMOS_DADOS_PESSOAIS = List.of(
            "senha",
            "cpf",
            "dados pessoais",
            "dados bancarios",
            "credenciais bancarias",
            "credenciais de acesso",
            "login do banco",
            "usuario do banco",
            "codigo de verificacao",
            "foto sua",
            "sua foto",
            "seu email",
            "seu e-mail",
            "endereco de email",
            "endereco de e-mail",
            "passa os 6 digitos",
            "passe os 6 digitos",
            "passar os 6 digitos",
            "digitos que chegaram",
            "numero do cartao",
            "dados do cartao",
            "validade do cartao",
            "codigo do cartao",
            "cvv",
            "cvc",
            "senha do banco",
            "senha bancaria",
            "senha do aplicativo",
            "senha do app",
            "senha da conta",
            "senha do pix",
            "senha de transacao",
            "senha eletronica",
            "pin do cartao",
            "pin da conta",
            "token de acesso",
            "token bancario",
            "codigo sms",
            "codigo por sms",
            "codigo recebido",
            "codigo que chegou",
            "codigo do whatsapp",
            "codigo do autenticador",
            "codigo de autenticacao",
            "codigo de seguranca",
            "codigo de recuperacao",
            "confirme o codigo",
            "informe o codigo",
            "manda o codigo",
            "passe o codigo",
            "chave de seguranca",
            "data de nascimento",
            "nome completo",
            "numero da conta",
            "numero da agencia",
            "agencia e conta",
            "numero do beneficio",
            "numero do nis",
            "numero do pis",
            "foto do documento",
            "foto do rg",
            "foto da cnh",
            "selfie com documento",
            "biometria facial"
    );

    // Solicitações de imagens ou dados que nunca devem ser enviados por mensagem.
    public static final List<String> TERMOS_SOLICITACAO_DADOS_SENSIVEIS = List.of(
            "envie foto frente e verso do cartao",
            "envie a foto frente e verso do cartao",
            "mande foto frente e verso do cartao",
            "mande a foto frente e verso do cartao",
            "foto da frente e verso do cartao",
            "foto do cartao frente e verso",
            "imagem da frente e verso do cartao",
            "envie foto da frente do cartao",
            "envie foto do verso do cartao",
            "mande foto da frente do cartao",
            "mande foto do verso do cartao",
            "envie imagem do cartao",
            "mande imagem do cartao",
            "compartilhe imagem do cartao",
            "anexe foto do cartao",
            "envie copia do cartao",
            "mande copia do cartao",
            "fotografe seu cartao",
            "tire foto do seu cartao",
            "mostre seu cartao pela camera",
            "mostre a frente do cartao",
            "mostre o verso do cartao",
            "envie o cartao completo",
            "mande o cartao completo",
            "envie os dados completos do cartao",
            "mande os dados completos do cartao",
            "envie o numero completo do cartao",
            "mande o numero completo do cartao",
            "envie a senha do cartao",
            "mande a senha do cartao",
            "envie o cvv do cartao",
            "mande o cvv do cartao",
            "envie o cvc do cartao",
            "mande o cvc do cartao",
            "envie a validade do cartao",
            "mande a validade do cartao",
            "envie foto do seu documento",
            "mande foto do seu documento",
            "envie documento frente e verso",
            "mande documento frente e verso",
            "envie rg frente e verso",
            "mande rg frente e verso",
            "envie cnh frente e verso",
            "mande cnh frente e verso",
            "envie selfie segurando documento",
            "mande selfie segurando documento",
            "envie selfie com o cartao",
            "mande selfie com o cartao",
            "envie comprovante do cartao",
            "mande comprovante do cartao",
            "envie print do cartao",
            "mande print do cartao",
            "envie captura do aplicativo bancario",
            "mande captura do aplicativo bancario",
            "envie print da conta bancaria",
            "mande print da conta bancaria",
            "envie extrato bancario completo",
            "mande extrato bancario completo",
            "envie comprovante de residencia",
            "mande comprovante de residencia"
    );

    // Pedidos diretos de credenciais bancárias ou códigos de autenticação.
    public static final List<String> TERMOS_PEDIDO_CREDENCIAIS = List.of(
            "passe seus dados do banco",
            "passe os dados do banco",
            "passa seus dados do banco",
            "passa os dados do banco",
            "passar seus dados do banco",
            "passar os dados do banco",
            "me passe seus dados do banco",
            "me passe os dados do banco",
            "mande seus dados do banco",
            "mande os dados do banco",
            "me mande seus dados do banco",
            "envie seus dados do banco",
            "envie os dados do banco",
            "me envie seus dados do banco",
            "informe seus dados bancarios",
            "informe os dados bancarios",
            "forneca seus dados bancarios",
            "forneca os dados bancarios",
            "compartilhe seus dados bancarios",
            "compartilhe os dados bancarios",
            "preciso dos seus dados bancarios",
            "precisamos dos seus dados bancarios",
            "passe os dados da sua conta",
            "mande os dados da sua conta",
            "envie os dados da sua conta",
            "informe os dados da sua conta",
            "passe seu login e senha",
            "passe o login e a senha",
            "mande seu login e senha",
            "envie seu login e senha",
            "informe seu login e senha",
            "digite seu login e senha",
            "confirme seu login e senha",
            "passe a senha do banco",
            "mande a senha do banco",
            "envie a senha do banco",
            "informe a senha do banco",
            "passe o codigo de verificacao",
            "mande o codigo de verificacao",
            "envie o codigo de verificacao",
            "informe o codigo de verificacao",
            "passe o codigo que chegou",
            "mande o codigo que chegou",
            "envie o codigo que chegou",
            "informe o codigo que chegou",
            "preciso da sua senha",
            "me diga o codigo de seis numeros",
            "codigo que acabou de chegar",
            "envie agencia, conta e cpf",
            "numero completo do cartao e a validade",
            "passe o token",
            "fotografe seu documento",
            "pin do seu cartao",
            "resposta da pergunta secreta",
            "print da tela inicial do banco",
            "usuario e a senha",
            "usuario e senha usados no internet banking"
    );

    // Frases usadas para alarmar a vítima sobre cartão e induzir o envio de dados.
    public static final List<String> TERMOS_CARTAO_COMPROMETIDO = List.of(
            "seu cartao foi bloqueado",
            "seu cartao esta bloqueado",
            "seu cartao sera bloqueado",
            "cartao bloqueado por seguranca",
            "cartao bloqueado por suspeita",
            "cartao bloqueado preventivamente",
            "cartao temporariamente bloqueado",
            "cartao suspenso",
            "cartao temporariamente suspenso",
            "cartao em analise",
            "cartao sob analise",
            "cartao com restricao",
            "cartao com uso restrito",
            "cartao com movimentacao suspeita",
            "cartao com transacao suspeita",
            "cartao com compra suspeita",
            "cartao com compra nao reconhecida",
            "cartao com tentativa de compra",
            "cartao com tentativa de uso",
            "cartao com tentativa de fraude",
            "cartao clonado",
            "cartao possivelmente clonado",
            "cartao comprometido",
            "cartao em risco",
            "cartao em validacao",
            "cartao precisa ser validado",
            "cartao precisa de confirmacao",
            "cartao precisa de atualizacao",
            "cartao precisa de desbloqueio",
            "desbloqueio do seu cartao",
            "regularize seu cartao",
            "atualize seu cartao",
            "confirme seu cartao",
            "confirme os dados do cartao",
            "valide os dados do cartao",
            "revisao do seu cartao",
            "revisao de seguranca do cartao",
            "alerta sobre seu cartao",
            "alerta de seguranca do cartao",
            "notificacao sobre seu cartao",
            "cartao com problema de seguranca",
            "cartao com atividade incomum",
            "cartao com atividade suspeita",
            "cartao utilizado em local incomum",
            "cartao usado sem autorizacao",
            "cartao usado por terceiros",
            "cartao com acesso nao autorizado",
            "cartao com pagamento nao reconhecido",
            "cartao com debito nao reconhecido",
            "cartao com saque nao reconhecido",
            "cartao com limite comprometido",
            "cartao com limite bloqueado",
            "cartao com funcao bloqueada",
            "cartao digital bloqueado",
            "cartao fisico bloqueado",
            "cartao cancelado por seguranca",
            "emissao de novo cartao",
            "solicite novo cartao",
            "substituicao do cartao",
            "bloqueio imediato do cartao"
    );

    // Orientações que indicam que a pessoa deve confirmar a informação fora da mensagem.
    public static final List<String> TERMOS_CANAL_OFICIAL = List.of(
            "canal oficial",
            "site oficial",
            "aplicativo oficial",
            "app oficial",
            "central oficial",
            "telefone oficial",
            "numero oficial",
            "agencia oficial",
            "procure o canal oficial",
            "acesse o canal oficial",
            "consulte o site oficial",
            "consulte diretamente a instituicao",
            "use o aplicativo oficial",
            "entre pelo aplicativo",
            "abra o aplicativo do banco",
            "nao clique em links",
            "nao clique no link",
            "digite o endereco do banco",
            "consulte diretamente o banco"
    );

    public static final List<String> INDICIOS_LINK = List.of(
            "http://",
            "https://",
            "www.",
            "bit.ly",
            "link:",
            "link.",
            "acesse:",
            "acesse o link",
            "abra o link",
            "link abaixo",
            "toque aqui",
            "clique aqui",
            "confira aqui",
            "bit.do",
            "tinyurl.com",
            "t.co",
            "cutt.ly",
            "encurtador.com.br"
    );

    public static final List<String> DOMINIOS_LINK = List.of(
            ".com",
            ".org",
            ".net",
            ".br",
            ".io",
            ".co",
            ".uk",
            ".eu",
            ".us",
            ".ca",
            ".de",
            ".fr",
            ".es",
            ".pt",
            ".xyz",
            ".top",
            ".digital",
            ".online",
            ".click",
            ".info",
            ".download",
            ".shop",
            ".site",
            ".live",
            ".store",
            ".app",
            ".it",
            ".nl",
            ".ru",
            ".cn",
            ".jp",
            ".in",
            ".au",
            ".mx",
            ".ar",
            ".xyz",
            ".top",
            ".site",
            ".online",
            ".info",
            ".biz",
            ".club",
            ".shop",
            ".live",
            ".click",
            ".link",
            ".me",
            ".tv",
            ".cc",
            ".tk"
    );

    /**
     * Domínios oficiais cadastrados. Subdomínios também são aceitos, por
     * exemplo, "ofertas.mercadolivre.com.br".
     */
    public static final List<String> DOMINIOS_OFICIAIS = List.of(
            "gov.br",
            "bb.com.br",
            "itau.com.br",
            "bradesco.com.br",
            "santander.com.br",
            "caixa.gov.br",
            "nubank.com.br",
            "bancointer.com.br",
            "c6bank.com.br",
            "btgpactual.com",
            "sicredi.com.br",
            "sicoob.com.br",
            "banrisul.com.br",
            "banestes.com.br",
            "bancopan.com.br",
            "original.com.br",
            "next.me",
            "neon.com.br",
            "willbank.com.br",
            "pagbank.com.br",
            "picpay.com",
            "mercadopago.com.br",
            "stone.com.br",
            "infinitepay.io",
            "recargapay.com.br",
            "mercadolivre.com",
            "mercadolivre.com.br",
            "amazon.com",
            "amazon.com.br",
            "shopee.com",
            "shopee.com.br",
            "magazineluiza.com.br",
            "magalu.com",
            "casasbahia.com.br",
            "ponto.com.br",
            "americanas.com.br",
            "kabum.com.br",
            "aliexpress.com",
            "shein.com",
            "temu.com",
            "olx.com.br",
            "ifood.com.br",
            "rappi.com.br",
            "netshoes.com.br",
            "centauro.com.br",
            "dafiti.com.br",
            "madeiramadeira.com.br",
            "leroymerlin.com.br",
            "carrefour.com.br",
            "extra.com.br",
            "fastshop.com.br"
    );

    /**
     * Marcas usadas para reconhecer variações visuais em domínios não
     * oficiais, como "mercad0livre.com".
     */
    public static final List<String> MARCAS_PROTEGIDAS = List.of(
            "gov",
            "mercadolivre",
            "mercadopago",
            "magazineluiza",
            "casasbahia",
            "madeiramadeira",
            "leroymerlin",
            "bancodobrasil",
            "bancointer",
            "btgpactual",
            "bradesco",
            "santander",
            "nubank",
            "c6bank",
            "sicredi",
            "sicoob",
            "banrisul",
            "banestes",
            "bancopan",
            "original",
            "pagbank",
            "picpay",
            "infinitepay",
            "recargapay",
            "amazon",
            "shopee",
            "magalu",
            "americanas",
            "kabum",
            "aliexpress",
            "shein",
            "temu",
            "netshoes",
            "centauro",
            "dafiti",
            "carrefour",
            "fastshop"
    );

    public static final List<String> PEDIDOS_ACAO = List.of(
            "vote em mim",
            "vote neste",
            "clique para votar",
            "cadastre-se",
            "retorne nesse contato",
            "retorne neste contato",
            "retorne o contato",
            "entre em contato",
            "responda essa mensagem",
            "responda esta mensagem",
            "chame no numero",
            "ligue para",
            "ligue",
            "me chama",
            "para retirar",
            "para tirar",
            "para receber",
            "para solicitar",
            "para ter direito",
            "pra resgatar",
            "resgate agora",
            "da um alo",
            "chama no zap",
            "me da um toque",
            "pra pegar",
            "para pegar",
            "confirme agora",
            "confirme seus dados",
            "confirme sua conta",
            "atualize seus dados",
            "atualize seu cadastro",
            "regularize sua conta",
            "desbloqueie sua conta",
            "libere seu acesso",
            "ative sua conta",
            "valide sua identidade",
            "valide seu cadastro",
            "fale comigo",
            "fala comigo",
            "chama aqui",
            "chama privado",
            "chama no privado",
            "me chama no privado",
            "manda mensagem",
            "mande mensagem",
            "responde aqui",
            "retorna aqui",
            "me liga",
            "liga pra mim",
            "salva esse numero",
            "adicione este numero"
    );

    /**
     * Extensões sem o ponto.
     * <p>
     * O ponto é adicionado pela expressão regular do analisador.
     */
    public static final List<String> ARQUIVOS_PERIGOSOS = List.of(
            "exe",
            "bat",
            "cmd",
            "scr",
            "msi",
            "jar",
            "apk",
            "xlsm",
            "docm",
            "pptm",
            "vbs",
            "ps1",
            "hta",
            "pif",
            "cpl",
            "reg",
            "wsf",
            "gadget",
            "application"
    );

    public static final List<String> TERMOS_TRANSFERENCIA = List.of(
            "pix",
            "transferencia",
            "deposito",
            "ted",
            "doc bancario",
            "boleto",
            "pagar boleto",
            "pagamento",
            "transferir",
            "transfere",
            "transfira",
            "depositar",
            "deposite",
            "mandar valor",
            "enviar valor",
            "chave pix",
            "copia e cola",
            "qr code pix",
            "pix copia e cola",
            "carteira digital",
            "recarga",
            "gift card",
            "cartao presente"
    );

    public static final List<String> TERMOS_MOEDAS = List.of(
            "real",
            "reais",
            "dolar",
            "dolares",
            "usd",
            "euro",
            "euros",
            "eur",
            "libra",
            "libras",
            "gbp",
            "peso",
            "pesos",
            "yen",
            "franco",
            "francos",
            "bitcoin",
            "btc",
            "ethereum",
            "eth",
            "cripto",
            "criptomoeda"
    );

    public static final List<String> DECLARACOES_ENVIO_LEGITIMO = List.of(
            "vou enviar",
            "vou mandar",
            "vou te enviar",
            "vou te mandar",
            "estou enviando",
            "te envio",
            "te mando",
            "te mandando",
            "vou fazer um pix",
            "vou fazer o pix",
            "vou transferir",
            "vou fazer uma transferencia",
            "vou pagar",
            "vou te pagar",
            "envio um pix",
            "envio o pix",
            "mando um pix",
            "mando o pix",
            "enviei um pix",
            "enviei",
            "mandei um pix",
            "mandei",
            "estou te pagando",
            "devo"
    );

    public static final List<String> DECLARACOES_TRANSFERENCIA_SUSPEITA = List.of(
            "estou te mandando",
            "estou mandando",
            "estou te enviando"
    );

    public static final List<String> TERMOS_MUDANCA_CONTATO = List.of(
            "esse e meu numero novo",
            "este e meu numero novo",
            "meu novo numero",
            "troquei de numero",
            "mudei de numero",
            "perdi meu zap antigo",
            "perdi meu whatsapp antigo",
            "meu cel foi pro saco",
            "meu celular foi pro saco",
            "aparelho de um parceiro",
            "aparelho de uma parceira",
            "troca meu contato",
            "troque meu contato",
            "numero antigo nao funciona",
            "nao uso mais o outro numero",
            "apaga meu numero antigo",
            "salva meu contato novo",
            "estou com outro chip",
            "to com outro chip",
            "celular quebrou",
            "celular estragou",
            "perdi meu celular",
            "roubaram meu celular",
            "estou usando outro aparelho",
            "to usando outro aparelho",
            "contato temporario",
            "whatsapp novo",
            "zap novo"
    );

    public static final List<String> PEDIDOS_DINHEIRO = List.of(
            "dinheiro emprestado",
            "preciso de dinheiro",
            "emprestimo",
            "um emprestimo",
            "fazer um emprestimo",
            "emprestar",
            "empresta",
            "me empresta",
            "consegue me emprestar",
            "quebrar um galho",
            "quebra um galho",
            "me quebrar um galho",
            "consegue me quebrar um galho",
            "dar uma ajuda",
            "me dar uma ajuda",
            "consegue me ajudar",
            "manda dinheiro",
            "mande dinheiro",
            "mandar um pix",
            "manda um pix",
            "fazer um pix",
            "faz um pix",
            "depois eu te pago",
            "me ajuda com dinheiro",
            "me ajuda com uma grana",
            "quebra essa pra mim",
            "faz essa pra mim",
            "to precisando de uma grana",
            "preciso de uma ajuda",
            "preciso pagar uma conta",
            "estou sem dinheiro",
            "to sem dinheiro",
            "adianta um valor",
            "adianta uma grana",
            "empresta uma grana",
            "manda uma ajuda",
            "faz um deposito",
            "paga pra mim"
    );

    public static final List<String> VERBOS_PEDIDO_VALOR = List.of(
            "manda",
            "mande",
            "manda ai",
            "mandar",
            "me manda",
            "envie",
            "pague",
            "apoiar",
            "apoie",
            "empresta",
            "empreste",
            "quebra",
            "adianta",
            "adiantar",
            "acerta",
            "taxinha de",
            "forca de",
            "faz a boa de",
            "entrar com",
            "contribui",
            "contribua",
            "colabora",
            "colabore",
            "desembolsa",
            "completa",
            "cobre",
            "banca",
            "antecipa",
            "antecipe",
            "faz chegar",
            "manda pra ca",
            "libera",
            "paga"
    );

    public static final List<String> PAGAMENTO_TERCEIROS = List.of(
            "pix do meu amigo",
            "pix de um amigo",
            "conta do meu amigo",
            "conta de um amigo",
            "conta de outra pessoa",
            "enviar direto pro",
            "enviar direto para",
            "mandar direto pro",
            "mandar direto para",
            "manda pro",
            "manda para",
            "mandar para",
            "direto para a loja",
            "conta do meu primo",
            "conta de um primo",
            "conta da minha prima",
            "conta de uma prima",
            "pix do meu parente",
            "pix de um parente",
            "conta do fornecedor",
            "conta do entregador",
            "conta do motoboy",
            "pix do vendedor",
            "pix da loja",
            "chave de outra pessoa",
            "titular diferente",
            "nome de outra pessoa",
            "conta de terceiro"
    );

    public static final List<String> TERMOS_AMEACA_BLOQUEIO = List.of(
            "conta bloqueada",
            "conta sera bloqueada",
            "conta suspensa",
            "acesso suspenso",
            "cartao bloqueado",
            "cartao sera cancelado",
            "cadastro irregular",
            "cadastro pendente",
            "cpf irregular",
            "cpf suspenso",
            "beneficio suspenso",
            "beneficio sera cancelado",
            "multa pendente",
            "divida pendente",
            "pagamento recusado",
            "compra suspeita",
            "transacao suspeita",
            "acesso nao reconhecido",
            "dispositivo desconhecido",
            "tentativa de acesso"
    );

    public static final List<String> TERMOS_FALSA_INSTITUICAO = List.of(
            "central de seguranca",
            "central antifraude",
            "setor antifraude",
            "equipe de seguranca",
            "suporte tecnico",
            "suporte do banco",
            "gerente da conta",
            "aqui e sua gerente",
            "aqui e seu gerente",
            "sou sua gerente",
            "sou seu gerente",
            "atendimento bancario",
            "representante do banco",
            "sou o dono do banco",
            "dono do banco",
            "sou o presidente do banco",
            "presidente do banco",
            "somos do banco",
            "falo em nome do banco",
            "equipe do pix",
            "central do cartao",
            "operadora do cartao",
            "receita federal",
            "correios informa",
            "mercado pago informa",
            "nubank informa",
            "caixa informa",
            "banco central informa",
            "aqui e seu advogado",
            "aqui e teu advogado",
            "sou seu advogado",
            "sou teu advogado",
            "escritorio de advocacia informa",
            "sou seu contador",
            "aqui e seu contador",
            "oficial de justica",
            "policia civil informa",
            "ministerio publico informa",
            "inss informa",
            "serasa informa",
            "sou o gerente",
            "i am the manager",
            "bank manager",
            "bank agent",
            "security team",
            "support agent",
            "soy el gerente",
            "gerente del banco",
            "soporte del banco",
            "je suis le directeur",
            "conseiller bancaire",
            "support bancaire"
    );

    public static final List<String> TERMOS_TAXA_ANTECIPADA = List.of(
            "taxa de liberacao",
            "taxa para liberar",
            "pague a taxa",
            "pagamento antecipado",
            "deposito antecipado",
            "taxa administrativa",
            "taxa de cadastro",
            "taxa de envio",
            "taxa de entrega",
            "taxa alfandegaria",
            "taxa dos correios",
            "taxa do premio",
            "custo de desbloqueio",
            "valor para liberar",
            "pagar para receber",
            "liberacao mediante pagamento",
            "frete pendente",
            "encomenda retida",
            "pacote retido",
            "pedido retido"
    );

    public static final List<String> TERMOS_INVESTIMENTO_SUSPEITO = List.of(
            "lucro garantido",
            "retorno garantido",
            "renda garantida",
            "ganho garantido",
            "investimento sem risco",
            "renda extra imediata",
            "dinheiro automatico",
            "multiplique seu dinheiro",
            "dobre seu dinheiro",
            "triplique seu dinheiro",
            "investimento secreto",
            "metodo infalivel",
            "robo de investimento",
            "sinais premium",
            "grupo vip de investimento",
            "rentabilidade garantida",
            "ganhe por dia",
            "saque imediato",
            "oportunidade imperdivel",
            "invista 500 e receba 5 mil",
            "robo de cripto nunca perde",
            "lucro diario",
            "dobre seu capital",
            "sinais secretos do mercado",
            "moeda vai subir 1.000%",
            "corretora privada",
            "renda passiva automatica",
            "multiplicar seu dinheiro",
            "emprestimo para aproveitar esta oportunidade",
            "transfira suas criptos",
            "receba o dobro",
            "saque apos uma ultima recarga",
            "recarga para liberar o saque"
    );

    public static final List<String> TERMOS_ACESSO_REMOTO = List.of(
            "instale anydesk",
            "baixe anydesk",
            "abra o anydesk",
            "instale teamviewer",
            "baixe teamviewer",
            "abra o teamviewer",
            "instale rustdesk",
            "baixe rustdesk",
            "acesso remoto",
            "controle remoto",
            "compartilhe sua tela",
            "compartilhar a tela",
            "mostre sua tela",
            "espelhe sua tela",
            "permita o acesso",
            "codigo do anydesk",
            "id do teamviewer",
            "senha do acesso remoto",
            "aplicativo de suporte",
            "app de suporte",
            "instale quicksupport",
            "baixe quicksupport",
            "instale supremo",
            "baixe supremo",
            "instale ultraviewer",
            "baixe ultraviewer",
            "instale aeroadmin",
            "baixe aeroadmin",
            "instale o supremo",
            "baixe o supremo",
            "instale o rustdesk",
            "baixe o rustdesk",
            "abra o quicksupport",
            "abra o rustdesk",
            "abra o supremo",
            "habilite o compartilhamento de tela",
            "ative o compartilhamento de tela",
            "informe o codigo de acesso remoto",
            "passe o codigo de acesso remoto",
            "controle seu computador",
            "controlar seu computador",
            "instale este apk",
            "habilite todo o conteudo",
            "desative o antivirus",
            "suporte remoto"
    );

    public static final List<String> TERMOS_PIX_ENGANO = List.of(
            "chegou um pix",
            "pix errado",
            "pix por engano",
            "manda de volta",
            "me devolva",
            "devolve o pix",
            "transferencia por engano",
            "transferencia errada",
            "paguei errado",
            "mandei errado",
            "mandei pra voce por engano",
            "chegou pra voce errado",
            "nao era pra ser seu",
            "preciso que devolva",
            "e meu dinheiro",
            "roubaram meu pix",
            "pix falso",
            "pix falsificado",
            "sem querer",
            "consegue me devolver",
            "consegue devolver",
            "manda pra mim de volta",
            "me devolve",
            "devolve rapidinho",
            "antes que o banco",
            "pra conta do meu amigo",
            "devolve agora",
            "devolve rapido",
            "quero de volta",
            "caiu um money"
    );

    public static final List<String> TERMOS_VERIFICACAO_IDENTIDADE = List.of(
            "confirme seus dados",
            "valide sua identidade",
            "valide sua conta",
            "valide seu cadastro",
            "atualize seu cadastro",
            "atualize seus dados",
            "regularize sua conta",
            "desbloqueie sua conta",
            "libere seu acesso",
            "ative sua conta",
            "reative sua conta",
            "confirme sua conta",
            "confirme sua identidade",
            "verifique sua identidade",
            "verifique sua conta",
            "atualize seus dados bancarios",
            "atualize suas informacoes",
            "confirme suas informacoes",
            "validacao de identidade",
            "verificacao de seguranca",
            "verificacao de conta",
            "confirmacao de dados",
            "confirme seus dados bancarios",
            "confirme os dados do banco",
            "valide seus dados bancarios",
            "valide os dados da conta",
            "atualize os dados da conta",
            "recadastre sua senha",
            "cadastre uma nova senha",
            "redefina sua senha",
            "confirme o codigo recebido",
            "valide o codigo recebido",
            "confirmar sua identidade",
            "recadastramento",
            "valide seus dados",
            "reative seu email",
            "atualize o whatsapp"
    );

    public static final List<String> TERMOS_PRESSAO_TEMPORAL = List.of(
            "preciso hoje",
            "preciso urgente",
            "preciso agora",
            "nao posso esperar",
            "nao tenho tempo",
            "e urgente mesmo",
            "e serio",
            "nao e brincadeira",
            "apura mesmo",
            "to em apuro",
            "estou em apuro",
            "e uma emergencia",
            "nao aguento mais",
            "nao aguento de verdade",
            "antes que seja tarde",
            "rapido que posso",
            "o mais rapido possivel",
            "nao consigo esperar"
    );

    public static final List<String> TERMOS_AMEACA_INFORMAL = List.of(
            "vai ficar irregular",
            "vai ficar suspenso",
            "vai ser bloqueado",
            "vou ter que fazer denuncia",
            "vou ter que denunciar",
            "vou ter que avisar o banco",
            "vou ter que avisar a policia",
            "vai dar problema",
            "vai dar ruim",
            "vai dar merda",
            "vai ficar em seu nome",
            "vai ficar em seu registro",
            "voce nao sabe o apuro que estou",
            "nao sabe o que to passando",
            "nao sabe como estou",
            "e meu ultimo recurso",
            "se nao conseguir ajuda",
            "se nao conseguir fazer isso"
    );

    public static final List<String> TERMOS_JUSTIFICATIVA_SUSPEITA = List.of(
            "meu banco bloqueou",
            "meu banco nao funciona",
            "meu cartao nao passa",
            "meu pix nao funciona",
            "problema com meu banco",
            "problema com meu pix",
            "nao consigo sacar",
            "nao consigo transferir",
            "minha conta esta travada",
            "minha conta esta bloqueada",
            "meu cartao foi cancelado",
            "meu cartao foi bloqueado",
            "passei o limite",
            "meu limite acabou",
            "meu acesso expirou",
            "meu acesso venceu"
    );

    public static final List<String> TERMOS_CONFIRMACAO_IMEDIATA = List.of(
            "responde rapido",
            "me responde agora",
            "preciso saber agora",
            "confirma pra mim",
            "confirma agora",
            "me avisa logo",
            "me chama pra confirmar",
            "ligar pra confirmar",
            "responde ja",
            "responde logo",
            "nao demore",
            "nao demora nao",
            "da um toque logo",
            "da um sinal",
            "me confirma",
            "confirma so",
            "confirma ai"
    );

    public static final List<String> TERMOS_COMPARECER_ENDERECO = List.of(
            "venha retirar",
            "compareca",
            "vem retirar",
            "va retirar",
            "precisa vir aqui",
            "precisa vir",
            "vai ter que vir",
            "tem que vir pessoalmente",
            "tem que aparecer aqui",
            "tem que aparecer",
            "apareca aqui",
            "apareca no endereco",
            "precisa aparecer",
            "precisa aparecer aqui",
            "vem aqui",
            "vem nessa",
            "vem so",
            "chega aqui",
            "chega no endereco",
            "passe por aqui",
            "passa por aqui",
            "va ate aqui",
            "va ate o endereco",
            "va para o endereco",
            "endereco tal",
            "na rua tal",
            "na avenida tal",
            "na nossa loja",
            "na loja",
            "no endereco da loja",
            "nos vemos",
            "a gente se ve",
            "se ve aqui",
            "em pessoa",
            "pessoalmente",
            "direto na loja",
            "vem buscar",
            "vem pegar",
            "vem receber",
            "precisa vir buscar",
            "precisa vir pegar",
            "venha ca",
            "vem ca",
            "vem para ca",
            "ta te esperando aqui",
            "estou te esperando aqui",
            "pode vir agora",
            "vem agora",
            "ja pode vir",
            "pode vir ja",
            "venha logo",
            "vem logo"
    );

    public static final List<String> TERMOS_EMERGENCIA_FINANCEIRA = List.of(
            "sem acesso a conta, paga",
            "fui assaltado, deposita",
            "compre cartoes-presente",
            "cartoes-presente e mande os codigos",
            "meu limite acabou, manda",
            "estou no hospital e preciso que pague",
            "seu filho foi detido",
            "nao avise ninguem, so envie o dinheiro",
            "parente sofreu acidente",
            "familiar sofreu acidente"
    );

    public static final List<String> TERMOS_ACAO_PHISHING = List.of(
            "conta tem uma pendencia",
            "evite o bloqueio",
            "compra desconhecida",
            "email sera encerrado",
            "e-mail sera encerrado",
            "intimacao anexada",
            "processo anexado",
            "mandado anexado",
            "formulario de verificacao"
    );

    public static final List<String> TERMOS_PREMIO_OU_BENEFICIO_FALSO = List.of(
            "ganhou um carro",
            "cpf foi sorteado",
            "beneficio esquecido",
            "cashback de",
            "restituicao disponivel",
            "cupom foi premiado",
            "ganhou uma viagem",
            "governo liberou um auxilio",
            "auxilio extra",
            "foi contemplado",
            "credito pre-aprovado sem consulta"
    );

    public static final List<String> TERMOS_GOLPE_ENTREGA = List.of(
            "encomenda ficou retida",
            "tarifa para entregar seu pacote",
            "imposto alfandegario pendente",
            "confirme pagando a nova tentativa",
            "taxa logistica",
            "despacho postal via pix",
            "seguro obrigatorio antes da entrega",
            "pacote esta no deposito",
            "codigo de retirada",
            "regularize a etiqueta",
            "multa na entrega",
            "so aceitamos transferencia"
    );

    public static final List<String> TERMOS_GOLPE_TRABALHO = List.of(
            "contratado, mas precisa pagar",
            "pagar o uniforme antes de comecar",
            "vaga home office",
            "compre nosso treinamento",
            "ganhe 800 por dia curtindo videos",
            "taxa de cadastro para enviar o equipamento",
            "tarefas simples e recarregue a plataforma",
            "pague o exame admissional",
            "trabalho garantido, envie foto dos documentos",
            "ativar seu salario, faca primeiro uma transferencia",
            "somos do rh, compre",
            "receba por avaliar produtos",
            "adicionar saldo a sua carteira"
    );

    public static final List<String> TERMOS_EXTORSAO_OU_COACAO = List.of(
            "tenho suas fotos intimas",
            "vou divulgar tudo sobre voce",
            "pague para eu nao enviar",
            "medico no exterior",
            "pagar uma passagem para te encontrar",
            "nao telefone para ele",
            "estamos com seu familiar",
            "nao chame a policia",
            "sou policial e seu nome apareceu",
            "retirar seu processo do sistema mediante deposito",
            "mandado contra voce",
            "resolva discretamente com esta transferencia",
            "computador foi filmado",
            "evitar a divulgacao"
    );

    public static final List<String> TERMOS_GOLPE_MARKETPLACE = List.of(
            "pagou a mais; devolva a diferenca",
            "receber pela venda, informe o codigo",
            "pix para aumentar o limite da carteira",
            "qr code para confirmar o recebimento",
            "segunda via com beneficiario atualizado",
            "compre gift cards",
            "foto dos codigos para quitar",
            "aproxime o cartao novamente sem olhar o valor",
            "comprador da olx",
            "confirme a venda pelo formulario",
            "deposito caucao para liberar o saldo",
            "transferencia de verificacao"
    );

    /*
     * Vocabulário estrutural. Diferentemente das listas acima, estes termos
     * representam partes de uma fraude e só pontuam quando combinados.
     */
    public static final List<String> VERBOS_SOLICITACAO = List.of(
            "fale",
            "diga",
            "informe",
            "confirme",
            "confirmar",
            "faca",
            "copie",
            "envie",
            "responda",
            "compartilhe",
            "passe",
            "mostre",
            "fotografe",
            "digite",
            "valide",
            "validar",
            "cadastre",
            "cadastrando",
            "atualize",
            "regularize",
            "recupere",
            "reative",
            "abra",
            "acesse",
            "entre",
            "clique",
            "leia",
            "escaneie",
            "instale",
            "baixe",
            "execute",
            "habilite",
            "desative",
            "aceite",
            "ligue",
            "procure",
            "consulte",
            "verifique",
            "confira",
            "send",
            "give",
            "share",
            "provide",
            "tell",
            "enter",
            "type",
            "upload",
            "forward",
            "envia",
            "enviame",
            "comparte",
            "dime",
            "confirma",
            "ingresa",
            "escribe",
            "manda",
            "envoyez",
            "partagez",
            "donnez",
            "confirmez",
            "saisissez"
    );

    public static final List<String> RADICAIS_SOLICITACAO = List.of(
            "inform",
            "confirm",
            "copi",
            "envi",
            "respond",
            "compartilh",
            "pass",
            "mostr",
            "fotograf",
            "valid",
            "cadastr",
            "atualiz",
            "regulariz",
            "recuper",
            "reativ",
            "abr",
            "acess",
            "clic",
            "escane",
            "instal",
            "baix",
            "execut",
            "habilit",
            "desativ",
            "deslig",
            "aceit",
            "procur",
            "consult",
            "verific",
            "confer",
            "precid",
            "prescis",
            "presis",
            "preciz",
            "ferific"
    );

    public static final List<String> ALVOS_DADOS_SENSIVEIS = List.of(
            "senha",
            "pin",
            "token",
            "codigo",
            "codigos",
            "cvv",
            "numeros do verso",
            "numero do cartao",
            "dados do cartao",
            "dados bancarios",
            "cartao",
            "card number",
            "credit card",
            "debit card",
            "bank card",
            "bank details",
            "account number",
            "personal information",
            "personal data",
            "id number",
            "date of birth",
            "numero de tarjeta",
            "tarjeta de credito",
            "tarjeta de debito",
            "datos bancarios",
            "numero de cuenta",
            "informacion personal",
            "documento de identidad",
            "fecha de nacimiento",
            "numero de carte",
            "carte bancaire",
            "carte de credit",
            "coordonnees bancaires",
            "numero de compte",
            "donnees personnelles",
            "date de naissance",
            "agencia",
            "conta",
            "cpf",
            "data de nascimento",
            "nome da mae",
            "documento",
            "documentos",
            "selfie",
            "biometria",
            "tela do banco",
            "movimentacoes",
            "pergunta secreta",
            "chave de recuperacao",
            "usuario"
    );

    public static final List<String> ALVOS_CREDENCIAIS_SECRETAS = List.of(
            "senha",
            "pin",
            "token",
            "codigo",
            "codigos",
            "cvv",
            "numeros do verso",
            "chave de recuperacao",
            "pergunta secreta",
            "security code",
            "security number",
            "password",
            "passcode",
            "otp",
            "one time password",
            "verification code",
            "authentication code",
            "access code",
            "codigo de seguridad",
            "contrasena",
            "clave",
            "codigo de verificacion",
            "codigo de autenticacion",
            "code de securite",
            "mot de passe",
            "code de verification",
            "code d'authentification"
    );

    public static final List<String> TERMOS_CARTAO_ESTRANGEIROS = List.of(
            "card",
            "tarjeta",
            "carte"
    );

    public static final List<String> TERMOS_NUMERO_MULTILINGUES = List.of(
            "numero",
            "number"
    );

    public static final List<String> RADICAIS_DADOS_SENSIVEIS = List.of(
            "cartao"
    );

    public static final List<String> TERMOS_IMAGEM_PESSOAL = List.of(
            "foto",
            "fotografia",
            "imagem",
            "selfie"
    );

    public static final List<String> TERMOS_ROSTO = List.of(
            "rosto",
            "biometria facial",
            "reconhecimento facial"
    );

    public static final List<String> VERBOS_ACAO_FINANCEIRA = List.of(
            "pague",
            "pagar",
            "deposite",
            "depositar",
            "transfira",
            "transferir",
            "mande dinheiro",
            "envie dinheiro",
            "envie",
            "compre",
            "comprar",
            "quite",
            "recarregue",
            "recarregar",
            "adicione saldo",
            "aplique",
            "aplicar",
            "invista",
            "investir",
            "repasse",
            "antecipe",
            "faca",
            "exige",
            "exija",
            "solicita um deposito",
            "solicita deposito",
            "escaneie",
            "leia",
            "leia o qr"
    );

    public static final List<String> RADICAIS_ACAO_FINANCEIRA = List.of(
            "pag",
            "deposit",
            "transfer",
            "envi",
            "compr",
            "quit",
            "recarreg",
            "adicion",
            "aplic",
            "invest",
            "repass",
            "antecip",
            "escane",
            "troc"
    );

    public static final List<String> ALVOS_FINANCEIROS = List.of(
            "pix",
            "ted",
            "transferencia",
            "deposito",
            "pagamento",
            "taxa",
            "tarifa",
            "boleto",
            "dinheiro",
            "saldo",
            "credito",
            "cartao-presente",
            "cartoes-presente",
            "gift card",
            "gift cards",
            "voucher",
            "vouchers",
            "bitcoin",
            "criptomoeda",
            "criptomoedas",
            "usdt",
            "carteira digital",
            "carteira de investimentos",
            "qr code",
            "caucao",
            "comissao",
            "comissoes",
            "seguro da transacao",
            "seguro de envio",
            "seguro da reserva",
            "seguro obrigatorio",
            "imposto",
            "honorarios",
            "recarga",
            "aporte",
            "rendimento",
            "fatura",
            "valor",
            "valores",
            "fundo",
            "selo digital",
            "cartoes",
            "qr",
            "mil",
            "ajuda financeira",
            "certificado",
            "reserva",
            "curso",
            "consulta medica",
            "armazenagem",
            "vale-presente"
    );

    public static final List<String> SINAIS_PRETEXTO_DE_GOLPE = List.of(
            "bloqueio",
            "cancelar",
            "liberar",
            "desbloquear",
            "regularizar",
            "pendencia",
            "cadastro",
            "reserva",
            "acidente",
            "cirurgia",
            "detido",
            "libertacao",
            "sequestrado",
            "emergencia",
            "sigilo",
            "segredo",
            "telefone de um amigo",
            "telefone caiu",
            "numero mudou",
            "conta nova",
            "conta de passagem",
            "prender",
            "prisao",
            "mandado",
            "multa",
            "premio",
            "ganhou",
            "beneficio",
            "restituicao",
            "emprestimo",
            "heranca",
            "loteria",
            "entrega",
            "encomenda",
            "pacote",
            "transportadora",
            "alfandega",
            "fiscalizacao",
            "vaga",
            "contratacao",
            "recrutador",
            "trabalho",
            "tarefas",
            "curso de integracao",
            "kit de trabalho",
            "uniforme",
            "venda",
            "comprador",
            "marketplace",
            "intermediador",
            "divulgar",
            "publicados",
            "vazamento",
            "imigracao",
            "avo",
            "vo",
            "irma",
            "marido",
            "esposa",
            "filho",
            "filha",
            "neto",
            "neta",
            "parente",
            "familia",
            "provar",
            "expirou",
            "expirada",
            "denunciado",
            "fatura corrigida",
            "secreto",
            "secretos",
            "bancos descubram",
            "diferenca de imposto",
            "valor excedente",
            "falso suporte",
            "fornecedor",
            "certificado obrigatorio",
            "home office",
            "notas fiscais",
            "rh",
            "admissao",
            "investigador",
            "denuncia",
            "inss",
            "financeira",
            "cartorio",
            "militar",
            "comprovante"
    );

    public static final List<String> TERMOS_CONTEXTO_COMERCIAL_EXPLICITO = List.of(
            "nota fiscal",
            "nf-e",
            "nfe",
            "emitir nota",
            "gerar a nota",
            "emissao da nota",
            "faturamento",
            "recibo do pagamento"
    );

    public static final List<String> TERMOS_ADMISSAO_FORMAL = List.of(
            "carteira de trabalho",
            "assinatura da carteira",
            "inicio das atividades",
            "processo de admissao",
            "registro do funcionario"
    );

    public static final List<String> TERMOS_LOGISTICA_ADMISSAO = List.of(
            "uniforme",
            "cracha",
            "foto 3x4",
            "tamanho de camisa",
            "tamanho de calca",
            "tamanho de calcado",
            "botina"
    );

    public static final List<String> SINAIS_PROMESSA_IRREAL = List.of(
            "rendimento fixo",
            "ao dia",
            "sem chance de prejuizo",
            "nao existe chance de prejuizo",
            "retorno certo",
            "retorno garantido",
            "lucro garantido",
            "automaticamente",
            "comissao dobrada",
            "ganhar todo dia",
            "dinheiro gratis",
            "multiplica",
            "vinte mil",
            "dez mil"
    );

    public static final List<String> SINAIS_CONTEXTO_INVESTIMENTO = List.of(
            "especialista opera",
            "investimento",
            "investidor",
            "investidores",
            "fundo exclusivo",
            "criptomoeda",
            "criptomoedas",
            "usdt",
            "algoritmo",
            "carteira de moedas",
            "rendimento",
            "saque",
            "retorno",
            "aporte"
    );

    public static final List<String> SINAIS_ACESSO_TECNICO = List.of(
            "compartilhe a tela",
            "espelhamento de tela",
            "controle do mouse",
            "controle do computador",
            "todas as permissoes",
            "teamviewer",
            "anydesk",
            "rustdesk",
            "quicksupport",
            "supremo",
            "ferramenta remota",
            "programa de assistencia",
            "fora da loja",
            "arquivo desconhecido",
            "habilite as macros",
            "desative a protecao",
            "desligue a protecao",
            "ignore o alerta",
            "suporte remoto"
    );

    public static final List<String> SINAIS_COACAO_GRAVE = List.of(
            "libertacao",
            "sob nosso controle",
            "sequestrado",
            "sequestrada",
            "serao publicados",
            "receberao as imagens",
            "apagar o video",
            "evitar vazamento",
            "nao envolva autoridades",
            "nao chame a policia"
    );

    public static final List<String> SINAIS_IDENTIDADE_FRAUDULENTA = List.of(
            "pessoa que conheceu online",
            "suposto militar",
            "suposta militar",
            "medico no exterior",
            "especialista desconhecido"
    );

    public static final List<String> MARCADORES_DE_RELATO = List.of(
            "recebi",
            "recebemos",
            "uma mensagem",
            "a mensagem",
            "um contato",
            "o contato",
            "uma pessoa",
            "um desconhecido",
            "o anuncio",
            "a proposta",
            "o vendedor",
            "o comprador",
            "o recrutador",
            "a empresa",
            "a plataforma",
            "a transportadora",
            "o suporte",
            "um tecnico",
            "um atendente",
            "o atendimento",
            "o banco solicita",
            "a loja informou",
            "o remetente",
            "suposta instituicao",
            "suposto militar",
            "alguem se apresentou",
            "mandaram",
            "prometeram",
            "a corretora",
            "uma corretora",
            "a entrevista",
            "o entregador",
            "um atendente",
            "o intermediador",
            "o cliente",
            "o caixa",
            "o boleto recebido",
            "chegou um boleto",
            "a conta do fornecedor",
            "uma consultoria",
            "fui convidado",
            "meu pacote",
            "a pessoa",
            "foi enviado"
    );

    public static final List<String> SINAIS_GERAIS_DE_RISCO = List.of(
            "urgente",
            "prazo termina",
            "pendencia",
            "solicitacao incomum",
            "atividade recente",
            "atividade incomum",
            "nao reconhecemos",
            "nao reconheca",
            "revisao de seguranca",
            "notificacao urgente",
            "compra que talvez",
            "compra nao reconhecida",
            "tentativa de acesso",
            "analise preventiva",
            "transferencia aguardando confirmacao",
            "divergencia no cadastro",
            "numero mudou",
            "conta do fornecedor mudou",
            "pagamento recusado",
            "link na mensagem",
            "pagina desconhecida",
            "endereco parece diferente",
            "endereco curto",
            "desconto alto",
            "rentabilidade acima da media",
            "corretora desconhecida",
            "ganhos rapidos",
            "criptomoedas",
            "enriqueceram rapidamente",
            "renda extra",
            "proposta de trabalho",
            "entrevista por mensagens",
            "documentos antes",
            "acima do mercado",
            "sem cnpj",
            "tarefas simples",
            "conta pessoal de mensagens",
            "dados bancarios",
            "total sigilo",
            "pendencia na entrega",
            "pacote atrasou",
            "pacote aparece como retido",
            "entrega sera cancelada",
            "remetente nao coincide",
            "ferramenta que nao conheco",
            "arquivo anexado",
            "permissoes maiores",
            "desativar temporariamente",
            "fora da loja oficial",
            "visualizar minha tela",
            "arquivo desconhecido",
            "permaneca ao telefone",
            "fora da plataforma",
            "saldo ainda nao apareceu",
            "valor maior por acidente",
            "beneficiario diferente",
            "mudou a forma de pagamento",
            "transportador que nao conheco",
            "pagamento pendente",
            "ajuda financeira",
            "ameaca divulgar",
            "processo que desconheco",
            "autoridade sem fornecer identificacao",
            "familiar e exige resposta rapida",
            "pede segredo",
            "beneficio sem ter feito solicitacao",
            "dinheiro esquecido",
            "vantajosa demais",
            "decisao imediata",
            "confirme uma informacao",
            "atualizacao importante",
            "ultima operacao",
            "dados continuam atualizados",
            "origem desta mensagem",
            "telefone desconhecido",
            "durante a ligacao",
            "transferencia recente",
            "pagamento do aluguel",
            "pix de cinquenta reais",
            "canal usado pela empresa",
            "conferencia bancaria",
            "endereco de rastreamento",
            "endereco parecido",
            "confirmar a reserva",
            "prazo muito reduzido",
            "poucas vagas",
            "entrevista sera feita",
            "antes da assinatura formal",
            "nem cnpj",
            "rastreamento mostra fiscalizacao",
            "confirmar o endereco por mensagem",
            "cobranca adicional de importacao",
            "nao coincide com o nome da loja",
            "erro apresentado no computador",
            "chamada de video",
            "email pedindo confirmacao",
            "pedindo confirmacao",
            "boleto atualizado",
            "contato exclusivamente por aplicativo",
            "acordo somente por mensagem"
    );

    /**
     * Regras que dependem apenas da presença de um conjunto de termos.
     * <p>
     * Regras compostas, como "promessa de dinheiro + link",
     * permanecem no DetectorGolpes.
     */
    public static final List<RegraGolpe> REGRAS_SIMPLES = List.of(
            new RegraGolpe(
                    TERMOS_URGENCIA,
                    2,
                    "A mensagem tenta criar urgência."
            ),
            new RegraGolpe(
                    TERMOS_PROMESSA_FINANCEIRA,
                    2,
                    "A mensagem promete prêmio, benefício ou ganho financeiro."
            ),
            new RegraGolpe(
                    TERMOS_DADOS_PESSOAIS,
                    4,
                    "A mensagem solicita dados pessoais ou bancários."
            ),
            new RegraGolpe(
                    TERMOS_SOLICITACAO_DADOS_SENSIVEIS,
                    4,
                    "A mensagem solicita imagens ou dados sensíveis de cartão, conta ou documento."
            ),
            new RegraGolpe(
                    PEDIDOS_ACAO,
                    2,
                    "A mensagem solicita que a pessoa realize uma ação."
            ),
            new RegraGolpe(
                    TERMOS_MUDANCA_CONTATO,
                    2,
                    "A mensagem informa uma mudança inesperada de contato."
            ),
            new RegraGolpe(
                    PAGAMENTO_TERCEIROS,
                    2,
                    "O pagamento solicitado seria enviado para outra pessoa."
            ),
            new RegraGolpe(
                    TERMOS_AMEACA_BLOQUEIO,
                    4,
                    "A mensagem ameaça bloquear ou suspender um serviço."
            ),
            new RegraGolpe(
                    TERMOS_FALSA_INSTITUICAO,
                    2,
                    "A mensagem tenta se apresentar como uma instituição ou suporte."
            ),
            new RegraGolpe(
                    TERMOS_TAXA_ANTECIPADA,
                    4,
                    "A mensagem cobra um valor antecipado para liberar algo."
            ),
            new RegraGolpe(
                    TERMOS_INVESTIMENTO_SUSPEITO,
                    7,
                    "A mensagem promete retorno financeiro fácil ou garantido."
            ),
            new RegraGolpe(
                    TERMOS_ACESSO_REMOTO,
                    7,
                    "A mensagem solicita acesso remoto ao dispositivo."
            ),
            new RegraGolpe(
                    TERMOS_PIX_ENGANO,
                    4,
                    "A mensagem solicita devolução de um valor supostamente enviado por PIX."
            ),
            new RegraGolpe(
                    TERMOS_VERIFICACAO_IDENTIDADE,
                    4,
                    "A mensagem solicita verificação de identidade ou de conta."
            ),
            new RegraGolpe(
                    TERMOS_PRESSAO_TEMPORAL,
                    4,
                    "A mensagem exerce pressão temporal para obter uma resposta ou pagamento."
            ),
            new RegraGolpe(
                    TERMOS_AMEACA_INFORMAL,
                    4,
                    "A mensagem usa ameaça ou pressão psicológica informal."
            ),
            new RegraGolpe(
                    TERMOS_JUSTIFICATIVA_SUSPEITA,
                    4,
                    "A mensagem usa uma justificativa financeira que deve ser verificada."
            ),
            new RegraGolpe(
                    TERMOS_CONFIRMACAO_IMEDIATA,
                    4,
                    "A mensagem exige confirmação imediata, sem tempo para análise."
            ),
            new RegraGolpe(
                    TERMOS_COMPARECER_ENDERECO,
                    2,
                    "A mensagem solicita comparecimento a um local que deve ser verificado."
            ),
            new RegraGolpe(
                    TERMOS_EMERGENCIA_FINANCEIRA,
                    7,
                    "A mensagem usa uma emergência como pretexto para pedir dinheiro."
            ),
            new RegraGolpe(
                    TERMOS_ACAO_PHISHING,
                    4,
                    "A mensagem usa um pretexto comum de phishing para induzir uma ação."
            ),
            new RegraGolpe(
                    TERMOS_PREMIO_OU_BENEFICIO_FALSO,
                    7,
                    "A mensagem anuncia prêmio, crédito ou benefício com sinais de fraude."
            ),
            new RegraGolpe(
                    TERMOS_GOLPE_ENTREGA,
                    7,
                    "A mensagem cobra pagamento suspeito relacionado a uma entrega."
            ),
            new RegraGolpe(
                    TERMOS_GOLPE_TRABALHO,
                    7,
                    "A mensagem condiciona trabalho ou remuneração a pagamento ou recarga."
            ),
            new RegraGolpe(
                    TERMOS_EXTORSAO_OU_COACAO,
                    7,
                    "A mensagem usa extorsão, ameaça ou coação para exigir pagamento."
            ),
            new RegraGolpe(
                    TERMOS_GOLPE_MARKETPLACE,
                    7,
                    "A mensagem usa um falso procedimento de compra, venda ou pagamento."
            )
    );

    private CatalogoGolpes() {
        // Impede a criação de instâncias.
    }
}
